version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mocktail-bird-service
    labels:
        com.mocktail.bird: "Mocktail-bird app container"
    ports:
      - "9080:9080"
    links:
      - db
    networks:
      - net-app-mongo
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 3
      labels:
          com.mocktail.bird: "Mocktail-bird app serivce"
  db:
    image: mongo:3.6.11-stretch
    container_name: mocktail-bird-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mockbird
      - MONGO_INITDB_ROOT_PASSWORD=Ilovethisbird
      - MONGO_INITDB_DATABASE=admin
    ports:
      - "27017:27017"
    volumes:
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mock-data:/data/db
    command: mongod --auth
    networks:
      - net-app-mongo
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 3
      labels:
          com.mocktail.bird.mongo: "Mocktail-bird mongo serivce"
volumes:
  mock-data:
networks:
  net-app-mongo:
    driver: "bridge"
